spring:
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/concurrency?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: Esperer123!

logging:
  level:
    org.springframework.r2dbc.core: debug